name: Publish to Pub.dev

on:
  push:
    branches:
      - master

jobs:
  publishing:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: 'Publish if new'
        id: publish
        uses: k-paxian/dart-package-publisher@master
        env:
          INPUT_FLUTTER: true
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          suppressBuildRunner: true
          
      - name: Tag commit
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
